import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

// Keep the crawlable page in sync with the same JSON and renderer used in-browser.
const root = fileURLToPath(new URL('../', import.meta.url));
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const data = JSON.parse(read('data/cv.json'));
const context = { window: {} };
vm.createContext(context);
vm.runInContext(read('assets/js/template-engine.js'), context);
const rendered = new context.window.CVTemplateEngine().render(data).trim().replace(/[ \t]+$/gm, '');
const url = new URL('/', data.basics.website).href;
const image = new URL(data.basics.image, url).href;
const title = `Oláh László – ${data.basics.label} | ${data.basics.location}`;
const description = 'Oláh László váci raktáros és targoncavezető önéletrajza. Raktári anyagmozgatás, komissiózás, áruösszekészítés és gépkezelői tapasztalat.';
const escape = value => String(value).replace(/[&<>"']/g, char => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
})[char]);
const profile = {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    '@id': `${url}#profile`,
    url,
    name: title,
    inLanguage: 'hu-HU',
    mainEntity: {
        '@type': 'Person',
        '@id': `${url}#person`,
        name: 'Oláh László',
        alternateName: data.basics.name,
        url,
        image,
        jobTitle: data.basics.label,
        description: data.summary.join(' '),
        homeLocation: { '@type': 'Place', name: data.basics.location },
        knowsAbout: data.skills.technical.flatMap(group => group.items.map(item => item.name))
    }
};
const metadata = `    <!-- SEO:START -->
    <title>${escape(title)}</title>
    <meta name="description" content="${escape(description)}">
    <link rel="canonical" href="${url}">
    <meta name="robots" content="index,follow,max-image-preview:large">
    <meta property="og:type" content="profile">
    <meta property="og:locale" content="hu_HU">
    <meta property="og:title" content="${escape(title)}">
    <meta property="og:description" content="${escape(description)}">
    <meta property="og:url" content="${url}">
    <meta property="og:image" content="${image}">
    <meta property="og:image:alt" content="Oláh László portréja">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="${escape(title)}">
    <meta name="twitter:description" content="${escape(description)}">
    <meta name="twitter:image" content="${image}">
    <script type="application/ld+json">${JSON.stringify(profile).replace(/</g, '\\u003c')}</script>
    <!-- SEO:END -->`;

let html = read('index.html');
if (!html.includes('<!-- SEO:START -->')) {
    html = html.replace(/    <title>[^<]*<\/title>\r?\n/, '')
        .replace(/    <meta name="description"[^>]*>\r?\n/, '')
        .replace('</head>', `${metadata}\n</head>`);
} else {
    html = html.replace(/    <!-- SEO:START -->[\s\S]*?<!-- SEO:END -->/, () => metadata);
}
const app = `    <div id="cv-app">\n        <!-- CV:START (generated by scripts/build-seo.mjs) -->\n${rendered}\n        <!-- CV:END -->\n    </div>`;
const appPattern = /    <div id="cv-app">[\s\S]*?(?=<!-- Template Engine -->)/;
if (!appPattern.test(html)) throw new Error('CV app container not found');
html = html.replace(appPattern, () => `${app}\n\n    `);
const outputs = new Map([
    ['index.html', html],
    ['robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${url}sitemap.xml\n`],
    ['sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${escape(url)}</loc></url>\n</urlset>\n`]
]);
for (const [file, content] of outputs) {
    if (process.argv.includes('--check')) {
        if (!fs.existsSync(path.join(root, file)) || read(file) !== content) {
            throw new Error(`${file} is out of date. Run node scripts/build-seo.mjs`);
        }
    } else {
        fs.writeFileSync(path.join(root, file), content);
    }
}
console.log(process.argv.includes('--check') ? 'SEO output is current.' : 'Generated crawlable CV, metadata, robots.txt and sitemap.xml.');
